[env]
TERM = "xterm-256color"

[font]
normal = { family = "Liberation Mono", style = "Regular" }
bold = { family = "Liberation Mono", style = "Bold" }
italic = { family = "Liberation Mono", style = "Italic" }
size = 12

[window]
decorations = "Full"
title = "terminal"

[colors.primary]
background = '#000000'
foreground = '#aaaaaa'

[colors.cursor]
cursor = '#00aa00'
text = '#000000'

[colors.normal]
black = '#000000'
blue = '#0000aa'
cyan = '#00aaaa'
green = '#00aa00'
red = '#aa0000'
magenta = '#aa00aa'
yellow = '#aa5500'
white = '#aaaaaa'

[colors.bright]
black = '#555555'
blue = '#5555ff'
green = '#55ff55'
cyan = '#55ffff'
red = '#ff5555'
magenta = '#ff55ff'
yellow = '#ffff55'
white = '#ffffff'

[colors.selection]
background = '#ffffff'
text = '#000000'
