[env]
TERM = "xterm-256color"

[font]
normal = { family = "Liberation Mono", style = "Regular" }
bold = { family = "Liberation Mono", style = "Bold" }
italic = { family = "Liberation Mono", style = "Italic" }
size = 12

[window]
decorations = "Full"
title = "terminal"

[colors.primary]
background = '0x000000'
foreground = '0xc4c4c4'

[colors.cursor]
cursor = '0x4edc4e'
text = '0x000000'

[colors.normal]
black = '0x000000'
blue = '0x0000c4'
cyan = '0x00c4c4'
green = '0x00c400'
red = '0xc40000'
magenta = '0xc400c4'
yellow = '0xc47e00'
white = '0xc4c4c4'

[colors.bright]
black = '0x4e4e4e'
blue = '0x4e4eff'
green = '0x4eff4e'
cyan = '0x4effff'
red = '0xff4e4e'
magenta = '0xff4eff'
yellow = '0xffff4e'
white = '0xffffff'

[colors.selection]
background = '0xffffff'
text = '0x000000'
